### ISSUE TITLE
Utility Helmet Armor

### ISSUE THREAD

**Issue by azurkutsuu** [abluescarab/tModLoader-QualityOfLifeRecipes#1]
I noticed in the Original Quality of Life mod the Mining Helmet upgrades counted for the Set bonus from the Mining gear, but so far in this upload and the "Re-Branded" upload the upgrades seem to have lost this attribute. I was wondering if it's possible to add this feature back to the items?

**Comment by abluescarab** [comment]
I'll see what I can do. Thanks for me letting me know.

**Comment by abluescarab** [comment]
This feature has been implemented in commit 9dbd5b79e434b320796a03ef3ddb9012d84c8bb4 and release [v1.2.0](https://github.com/abluescarab/tModLoader-QualityOfLifeRecipes/releases/tag/v1.2.0). Feel free to open a new issue if you have any more problems or requests!
