### ISSUE TITLE
Undead Banner not including Demon Eyes

### ISSUE THREAD

**Issue by BratrilliantG7** [abluescarab/tModLoader-QualityOfLifeRecipes#2]
The Undead Banner, which is supposed to combine Zombies, Raincoat Zombies, and Demon Eyes, only provides a boost against Zombies and Raincoat Zombies.
![qolbug1](https://user-images.githubusercontent.com/20077288/33701630-46ef4f4e-dae5-11e7-9a2c-1180ad99a4ae.png)

I have tested using no banners, only the Undead Banner, and only the Demon Eye banner, and with the Undead Banner, damage against Demon Eyes is the same as having no banners active so it isn't just a visual bug.

**Comment by abluescarab** [comment]
Thanks for letting me know! This should be fixed in release [v1.2.2](https://github.com/abluescarab/tModLoader-QualityOfLifeRecipes/releases/tag/v1.2.2).
